### PR TITLE
Merges `master` into `main`

### LINKED ISSUE #7: default branch flow
There is now a branch named "main", and a branch named "master", but the default branch is still "master"

- [x] Update the repository so that the default branch becomes `main`

- [x] delete master branch, taking care of finishing ongoing Pull Requests

### PR DESCRIPTION
**Pull request by kuzeko**
@IKnowLogic  please let me know if this is all fine, then let's switch all to `main` for this repo.

This closed #7

### CODE REVIEW

**Review by tngTUDOR — CHANGES_REQUESTED** [review]
I suggest we upgrade the version to 0.5.0, since this new version in the default branch breaks compatibility with previous one (the `cli` tool has new and different options).
solved with: e70acdb

**Review by tngTUDOR — APPROVED** [review]

**Review by tngTUDOR — COMMENTED** [review]
@IKnowLogic & @kuzeko please verify that this is what you intended, I have no experience in this specific part of the code:

```python
prov = Namespace("http://www.w3.org/ns/prov#"
```
for foaf and for metadata

**Comment by IKnowLogic** [comment]
@tngTUDOR Yes, that is intended, that is the namespace of the W3 PROV Ontology.
@kuzeko All looks well, you are welcome to merge.

**Review by IKnowLogic — APPROVED** [review]

**Comment by kuzeko** [comment]
`master` is no more

**Pull request merged**
